version: '3.8'

services:
#  backend:
#    build:
#      context: ./backend
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/prompt_center
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=postgres
#      - SPRING_REDIS_HOST=redis
#      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
#    depends_on:
#      - db
#      - redis
#      - elasticsearch
#    volumes:
#      - ./backend:/app
#    networks:
#      - prompt-network

#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    ports:
#      - "3000:3000"
#    volumes:
#      - ./frontend:/app
#      - /app/node_modules
#    depends_on:
#      - backend
#    networks:
#      - prompt-network

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prompt_center
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - prompt-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - prompt-network

  elasticsearch:
    image: elasticsearch:8.11.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - prompt-network

volumes:
  postgres_data:
  redis_data:
  elasticsearch_data:

networks:
  prompt-network:
    driver: bridge
