spring:
  application:
    name: prompt-center
  datasource:
    url: jdbc:postgresql://localhost:5432/prompt_center
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  redis:
    host: localhost
    port: 6379
  elasticsearch:
    uris: http://localhost:9200
  security:
    jwt:
      secret: your-secret-key-here
      expiration: 691200000  # 8 days in milliseconds

server:
  port: 8080
  servlet:
    context-path: /api/v1

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

logging:
  level:
    root: INFO
    com.promptcenter: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG 