spring:
  profiles:
    active: local
  application:
    name: prompt-center
  datasource:
    url: jdbc:postgresql://localhost:5432/prompt_center
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  # 현재는 jpa-ddl-auto: validate 사용중 - local.yml 에서 설정
  # flyway: # 나중에 도입할 때 활성화
  #   enabled: true
  #   baseline-on-migrate: true
  #   locations: classpath:db/migration
  redis:
    host: localhost
    port: 6379
  elasticsearch:
    uris: http://localhost:9200

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

logging:
  level:
    root: INFO
    com.promptcenter: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG

management:
  server:
    base-path: /actuator
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

init:
  category:
    data: true
