spring:
  jpa:
    hibernate:
      ddl-auto: create-drop  # 로컬 환경에서는 애플리케이션 종료 시 데이터베이스 초기화
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    com.gongdel.promptserver: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE  # SQL 파라미터 로깅 활성화

init:
  category:
    data: false
