spring:
  # 로컬 개발환경용 인프라 설정
  datasource:
    url: jdbc:postgresql://localhost:5432/prompt_center_dev
    username: prompth_user
    password: dev_password_123
  data:
    redis:
      host: localhost
      port: 6379
      password: # 로컬에서는 비밀번호 없음
  elasticsearch:
    uris: http://localhost:9200

  jpa:
    hibernate:
      ddl-auto: validate  # Flyway 마이그레이션만 사용
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true

logging:
  level:
    root: INFO
    com.gongdel.promptserver: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE  # SQL 파라미터 로깅 활성화
    org.springframework.security: DEBUG

server:
  error:
    include-message: on-param
    include-binding-errors: on-param
    include-stacktrace: on-param
